/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f7f9ff',
        'surface-dim': '#d1dbe8',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf4ff',
        'surface-container': '#e4effd',
        'surface-container-high': '#dfe9f7',
        'surface-container-highest': '#d9e3f1',
        'on-surface': '#121d26',
        'on-surface-variant': '#424845',
        'inverse-surface': '#27313c',
        'inverse-on-surface': '#e8f2ff',
        outline: '#727975',
        'outline-variant': '#c1c8c4',
        'surface-tint': '#4a645b',
        primary: '#00130d',
        'on-primary': '#ffffff',
        'primary-container': '#0f2922',
        'on-primary-container': '#769188',
        'inverse-primary': '#b0cdc2',
        secondary: '#775a19',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdd487',
        'on-secondary-container': '#785a19',
        tertiary: '#00130a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002b1b',
        'on-tertiary-container': '#009f6e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#cce9de',
        'primary-fixed-dim': '#b0cdc2',
        'on-primary-fixed': '#052019',
        'on-primary-fixed-variant': '#324c44',
        'secondary-fixed': '#ffdea4',
        'secondary-fixed-dim': '#e8c176',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4200',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        background: '#f7f9ff',
        'on-background': '#121d26',
        'surface-variant': '#d9e3f1',
      },
      fontFamily: {
        'display-hero': ['"Playfair Display"', 'serif'],
        'display-hero-mobile': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'title-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', fontWeight: '600' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', fontWeight: '600' }],
        'headline-lg': ['38px', { lineHeight: '46px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['26px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '700' }],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'max-width-content': '1280px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
